services:
  password-cracker-central-server:
    build:
      context: "./Backend/Central_server"
      dockerfile: Dockerfile
    volumes:
      - "./Backend/Central_server:/App"
    ports:
      - "5098:5098"
    depends_on:
      - password-cracker-database
    networks:
      - password-cracker-network

  password-cracker-database:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: password_cracker_db
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - password-cracker-network
    ports:
      - "5432:5432"

networks:
  password-cracker-network:
    driver: bridge

volumes:
  db_data: